apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: azfuncdemo
  name: azfunchttpexample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azfunchttpexample
  template:
    metadata:
      labels:
        app: azfunchttpexample
    spec:
      nodeSelector:
        'kubernetes.io/os': linux
      containers:
        - name: azfunchttpexample
          image: nvhoanganh1909/azurefuncdockernewrelicchildlinux:v1.0.15
          env:
            - name: NEW_RELIC_APPLICATION_LOGGING_ENABLED
              value: "true"
            - name: NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED
              value: "true"
            - name: NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED
              value: "10000"
            - name: NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED
              value: "false"
            - name: NEW_RELIC_AZURE_FUNCTION_MODE_ENABLED
              value: "1"
            - name: NEW_RELIC_APP_NAME
              value: "Azure Function in Docker Sample"
            - name: NEW_RELIC_LICENSE_KEY
              value: ""
            - name: AzureWebJobsStorage
              value: ""
            - name: SqlConnection
              value: ""
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 400Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: childservice
spec:
  selector:
    app: azfunchttpexample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azfunchttpexampleparent
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: azfunchttpexampleparent
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: azfunchttpexampleparent
