###
# while running func start (via func start)
@host = http://localhost:7071
# while running inside local docker (via docker run)
# @host = http://localhost:8080
# # # while running in Azure AKS
# this is the AI endpoint
@host = http://4.237.144.200
# # # this is the New Relic endpoint
@host = http://4.200.97.152

###
GET {{host}}/api/HttpExampleParent


###
GET {{host}}/api/HttpExampleChild

