apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: azfuncdemo
  name: azfunchttpexampleparent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azfunchttpexampleparent
  template:
    metadata:
      labels:
        app: azfunchttpexampleparent
    spec:
      nodeSelector:
        'kubernetes.io/os': linux
      containers:
        - name: azfunchttpexampleparent
          image: nvhoanganh1909/azurefuncdockernewrelicparentlinux:v1.0.14
          env:
            - name: NEW_RELIC_APP_NAME
              value: "Azure Function in Docker Sample - Parent"
            - name: NEW_RELIC_LICENSE_KEY
              value: ""
            - name: AzureWebJobsStorage
              value: ""
            - name: CHILD_SERVICE_HOST
              value: "childservice"
            - name: QUEUE_NAME
              value: "testqueuenewrelic"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azfunchttpexampleparent
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: azfunchttpexampleparent
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: azfunchttpexampleparent
